"""baseline: full schema 2026-07-10

Revision ID: 404cab2e5e0c
Revises: 
Create Date: 2026-07-10 09:42:08.605325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404cab2e5e0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('subject_code', sa.String(length=30), nullable=False),
    sa.Column('name_vi', sa.String(length=200), nullable=False),
    sa.Column('name_short', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('grade_min', sa.Integer(), nullable=False),
    sa.Column('grade_max', sa.Integer(), nullable=False),
    sa.Column('parent_code', sa.String(length=30), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_code'], ['subject.subject_code'], ),
    sa.PrimaryKeyConstraint('subject_code')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index('ix_subject_category', ['category'], unique=False)
        batch_op.create_index('ix_subject_grade_range', ['grade_min', 'grade_max'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.subject_code'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_class_id'), ['id'], unique=False)
        batch_op.create_index('ix_class_teacher_active', ['teacher_id', 'is_active'], unique=False)

    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('section_code', sa.String(length=30), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.String(length=300), nullable=False),
    sa.Column('lesson_no', sa.Integer(), nullable=False),
    sa.Column('lesson_title', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.subject_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_code', 'grade', 'section_code', 'chapter_no', 'lesson_no', name='uq_curriculum_subject')
    )
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.create_index('ix_curriculum_grade', ['grade'], unique=False)
        batch_op.create_index('ix_curriculum_grade_chapter', ['grade', 'chapter_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_id'), ['id'], unique=False)
        batch_op.create_index('ix_curriculum_subject_grade', ['subject_code', 'grade'], unique=False)

    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(length=32), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('layout_json', sa.Text(), nullable=True),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.subject_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index('ix_exam_hash_status', ['file_hash', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_id'), ['id'], unique=False)
        batch_op.create_index('ix_exam_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.subject_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.create_index('ix_quiz_created_at', ['created_by_id', 'created_at'], unique=False)
        batch_op.create_index('ix_quiz_created_by', ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_id'), ['id'], unique=False)
        batch_op.create_index('ix_quiz_status_visibility', ['status', 'visibility'], unique=False)
        batch_op.create_index('ix_quiz_subject_grade', ['subject_code', 'grade'], unique=False)

    op.create_table('teacherpage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacherpage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacherpage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacherpage_slug'), ['slug'], unique=True)

    op.create_table('yccd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('strand', sa.String(length=150), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.subject_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('yccd', schema=None) as batch_op:
        batch_op.create_index('ix_yccd_grade', ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_yccd_id'), ['id'], unique=False)
        batch_op.create_index('ix_yccd_subject_grade', ['subject_code', 'grade'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('show_answer', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_class_active', ['class_id', 'is_active'], unique=False)
        batch_op.create_index('ix_assignment_class_deadline', ['class_id', 'deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_id'), ['id'], unique=False)
        batch_op.create_index('ix_assignment_quiz', ['quiz_id'], unique=False)

    op.create_table('classmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classmember', schema=None) as batch_op:
        batch_op.create_index('ix_classmember_class_student', ['class_id', 'student_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_classmember_id'), ['id'], unique=False)
        batch_op.create_index('ix_classmember_student', ['student_id'], unique=False)

    op.create_table('curriculum_yccd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('yccd_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yccd_id'], ['yccd.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'yccd_id', name='uq_curriculum_yccd')
    )
    with op.batch_alter_table('curriculum_yccd', schema=None) as batch_op:
        batch_op.create_index('ix_curriculum_yccd_curriculum', ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_yccd_id'), ['id'], unique=False)
        batch_op.create_index('ix_curriculum_yccd_yccd', ['yccd_id'], unique=False)

    op.create_table('documentasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('provenance_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('documentasset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentasset_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentasset_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentasset_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentasset_user_id'), ['user_id'], unique=False)

    op.create_table('lesson_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('bo_sach', sa.String(length=60), nullable=False),
    sa.Column('so_tiet', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('template', sa.String(length=40), nullable=False),
    sa.Column('model_used', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_plan', schema=None) as batch_op:
        batch_op.create_index('ix_lesson_plan_curriculum', ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_plan_id'), ['id'], unique=False)
        batch_op.create_index('ix_lesson_plan_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=True),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.String(length=200), nullable=True),
    sa.Column('lesson_title', sa.String(length=200), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_source', sa.String(length=20), nullable=True),
    sa.Column('solution_steps', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_bank_duplicate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=True),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.subject_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_id'), ['id'], unique=False)
        batch_op.create_index('ix_question_public_created', ['is_public', 'created_at'], unique=False)
        batch_op.create_index('ix_question_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_question_user_difficulty', ['user_id', 'difficulty'], unique=False)
        batch_op.create_index('ix_question_user_grade', ['user_id', 'grade'], unique=False)
        batch_op.create_index('ix_question_user_grade_chapter', ['user_id', 'grade', 'chapter'], unique=False)
        batch_op.create_index('ix_question_user_hash', ['user_id', 'content_hash'], unique=False)
        batch_op.create_index('ix_question_user_subject', ['user_id', 'subject_code'], unique=False)
        batch_op.create_index('ix_question_user_subject_grade', ['user_id', 'subject_code', 'grade'], unique=False)
        batch_op.create_index('ix_question_user_topic', ['user_id', 'topic'], unique=False)
        batch_op.create_index('ix_question_user_topic_diff', ['user_id', 'topic', 'difficulty'], unique=False)
        batch_op.create_index('ix_question_user_type', ['user_id', 'question_type'], unique=False)
        batch_op.create_index('ix_question_user_type_topic_diff', ['user_id', 'question_type', 'topic', 'difficulty'], unique=False)

    op.create_table('questiondraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cau_num', sa.Integer(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.String(length=200), nullable=True),
    sa.Column('lesson_title', sa.String(length=200), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_source', sa.String(length=20), nullable=True),
    sa.Column('solution_steps', sa.Text(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('source_block_ids_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questiondraft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questiondraft_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questiondraft_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questiondraft_user_id'), ['user_id'], unique=False)

    op.create_table('quiztheory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiztheory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiztheory_id'), ['id'], unique=False)
        batch_op.create_index('ix_quiztheory_quiz', ['quiz_id'], unique=False)

    op.create_table('questionasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['documentasset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'asset_id', name='uq_questionasset_question_asset')
    )
    with op.batch_alter_table('questionasset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionasset_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionasset_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionasset_question_id'), ['question_id'], unique=False)

    op.create_table('questiondraftasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['documentasset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['questiondraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'asset_id', name='uq_questiondraftasset_draft_asset')
    )
    with op.batch_alter_table('questiondraftasset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questiondraftasset_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questiondraftasset_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questiondraftasset_id'), ['id'], unique=False)

    op.create_table('questionreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'reporter_id', name='uq_report_question_user')
    )
    with op.batch_alter_table('questionreport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionreport_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionreport_question_id'), ['question_id'], unique=False)

    op.create_table('quizattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('selected_question_ids', sa.JSON(), nullable=True),
    sa.Column('time_spent_s', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('graded_by_id', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['graded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.create_index('ix_quizattempt_assignment', ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizattempt_id'), ['id'], unique=False)
        batch_op.create_index('ix_quizattempt_quiz_student', ['quiz_id', 'student_id'], unique=False)
        batch_op.create_index('ix_quizattempt_status', ['quiz_id', 'status'], unique=False)
        batch_op.create_index('ix_quizattempt_student', ['student_id', 'created_at'], unique=False)

    op.create_table('quiztheorysection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theory_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.String(length=20), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['theory_id'], ['quiztheory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiztheorysection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiztheorysection_id'), ['id'], unique=False)
        batch_op.create_index('ix_quiztheorysection_theory_order', ['theory_id', 'order'], unique=False)

    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_q', sa.Integer(), nullable=True),
    sa.Column('correct_q', sa.Integer(), nullable=True),
    sa.Column('time_spent_s', sa.Integer(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=True),
    sa.Column('game_mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index('ix_submission_assignment_student', ['assignment_id', 'student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_id'), ['id'], unique=False)
        batch_op.create_index('ix_submission_student', ['student_id'], unique=False)

    op.create_table('answerdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('given_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answerdetail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answerdetail_id'), ['id'], unique=False)
        batch_op.create_index('ix_answerdetail_submission', ['submission_id'], unique=False)

    op.create_table('quizquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('origin_question_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('origin_quiz_code', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('has_correct_answer', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('scoring', sa.JSON(), nullable=True),
    sa.Column('solution', sa.JSON(), nullable=True),
    sa.Column('hint_section_id', sa.Integer(), nullable=True),
    sa.Column('hint_auto_linked', sa.Boolean(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hint_section_id'], ['quiztheorysection.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_question_id'], ['question.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.subject_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizquestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizquestion_id'), ['id'], unique=False)
        batch_op.create_index('ix_quizquestion_origin', ['origin_question_id'], unique=False)
        batch_op.create_index('ix_quizquestion_quiz_order', ['quiz_id', 'order'], unique=False)
        batch_op.create_index('ix_quizquestion_quiz_type', ['quiz_id', 'type'], unique=False)

    op.create_table('ieltswritinggrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('grade_hash', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=10), nullable=False),
    sa.Column('band_ta', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('band_cc', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('band_lr', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('band_gra', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('band_overall', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('feedback_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quizattempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quizquestion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ieltswritinggrade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ieltswritinggrade_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ieltswritinggrade_grade_hash'), ['grade_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ieltswritinggrade_id'), ['id'], unique=False)
        batch_op.create_index('ix_iwg_attempt_question', ['attempt_id', 'question_id'], unique=False)
        batch_op.create_index('ix_iwg_hash_status', ['grade_hash', 'status'], unique=False)

    op.create_table('quizanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('given_answer', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=True),
    sa.Column('hint_level', sa.Integer(), nullable=True),
    sa.Column('teacher_comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quizattempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quizquestion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizanswer', schema=None) as batch_op:
        batch_op.create_index('ix_quizanswer_attempt', ['attempt_id'], unique=False)
        batch_op.create_index('ix_quizanswer_attempt_question', ['attempt_id', 'question_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_quizanswer_id'), ['id'], unique=False)
        batch_op.create_index('ix_quizanswer_question', ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizanswer', schema=None) as batch_op:
        batch_op.drop_index('ix_quizanswer_question')
        batch_op.drop_index(batch_op.f('ix_quizanswer_id'))
        batch_op.drop_index('ix_quizanswer_attempt_question')
        batch_op.drop_index('ix_quizanswer_attempt')

    op.drop_table('quizanswer')
    with op.batch_alter_table('ieltswritinggrade', schema=None) as batch_op:
        batch_op.drop_index('ix_iwg_hash_status')
        batch_op.drop_index('ix_iwg_attempt_question')
        batch_op.drop_index(batch_op.f('ix_ieltswritinggrade_id'))
        batch_op.drop_index(batch_op.f('ix_ieltswritinggrade_grade_hash'))
        batch_op.drop_index(batch_op.f('ix_ieltswritinggrade_attempt_id'))

    op.drop_table('ieltswritinggrade')
    with op.batch_alter_table('quizquestion', schema=None) as batch_op:
        batch_op.drop_index('ix_quizquestion_quiz_type')
        batch_op.drop_index('ix_quizquestion_quiz_order')
        batch_op.drop_index('ix_quizquestion_origin')
        batch_op.drop_index(batch_op.f('ix_quizquestion_id'))

    op.drop_table('quizquestion')
    with op.batch_alter_table('answerdetail', schema=None) as batch_op:
        batch_op.drop_index('ix_answerdetail_submission')
        batch_op.drop_index(batch_op.f('ix_answerdetail_id'))

    op.drop_table('answerdetail')
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_student')
        batch_op.drop_index(batch_op.f('ix_submission_id'))
        batch_op.drop_index('ix_submission_assignment_student')

    op.drop_table('submission')
    with op.batch_alter_table('quiztheorysection', schema=None) as batch_op:
        batch_op.drop_index('ix_quiztheorysection_theory_order')
        batch_op.drop_index(batch_op.f('ix_quiztheorysection_id'))

    op.drop_table('quiztheorysection')
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.drop_index('ix_quizattempt_student')
        batch_op.drop_index('ix_quizattempt_status')
        batch_op.drop_index('ix_quizattempt_quiz_student')
        batch_op.drop_index(batch_op.f('ix_quizattempt_id'))
        batch_op.drop_index('ix_quizattempt_assignment')

    op.drop_table('quizattempt')
    with op.batch_alter_table('questionreport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionreport_question_id'))
        batch_op.drop_index(batch_op.f('ix_questionreport_id'))

    op.drop_table('questionreport')
    with op.batch_alter_table('questiondraftasset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questiondraftasset_id'))
        batch_op.drop_index(batch_op.f('ix_questiondraftasset_draft_id'))
        batch_op.drop_index(batch_op.f('ix_questiondraftasset_asset_id'))

    op.drop_table('questiondraftasset')
    with op.batch_alter_table('questionasset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionasset_question_id'))
        batch_op.drop_index(batch_op.f('ix_questionasset_id'))
        batch_op.drop_index(batch_op.f('ix_questionasset_asset_id'))

    op.drop_table('questionasset')
    with op.batch_alter_table('quiztheory', schema=None) as batch_op:
        batch_op.drop_index('ix_quiztheory_quiz')
        batch_op.drop_index(batch_op.f('ix_quiztheory_id'))

    op.drop_table('quiztheory')
    with op.batch_alter_table('questiondraft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questiondraft_user_id'))
        batch_op.drop_index(batch_op.f('ix_questiondraft_id'))
        batch_op.drop_index(batch_op.f('ix_questiondraft_exam_id'))

    op.drop_table('questiondraft')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('ix_question_user_type_topic_diff')
        batch_op.drop_index('ix_question_user_type')
        batch_op.drop_index('ix_question_user_topic_diff')
        batch_op.drop_index('ix_question_user_topic')
        batch_op.drop_index('ix_question_user_subject_grade')
        batch_op.drop_index('ix_question_user_subject')
        batch_op.drop_index('ix_question_user_hash')
        batch_op.drop_index('ix_question_user_grade_chapter')
        batch_op.drop_index('ix_question_user_grade')
        batch_op.drop_index('ix_question_user_difficulty')
        batch_op.drop_index('ix_question_user_created')
        batch_op.drop_index('ix_question_public_created')
        batch_op.drop_index(batch_op.f('ix_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_content_hash'))

    op.drop_table('question')
    with op.batch_alter_table('lesson_plan', schema=None) as batch_op:
        batch_op.drop_index('ix_lesson_plan_user_created')
        batch_op.drop_index(batch_op.f('ix_lesson_plan_id'))
        batch_op.drop_index('ix_lesson_plan_curriculum')

    op.drop_table('lesson_plan')
    with op.batch_alter_table('documentasset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentasset_user_id'))
        batch_op.drop_index(batch_op.f('ix_documentasset_id'))
        batch_op.drop_index(batch_op.f('ix_documentasset_exam_id'))
        batch_op.drop_index(batch_op.f('ix_documentasset_content_hash'))

    op.drop_table('documentasset')
    with op.batch_alter_table('curriculum_yccd', schema=None) as batch_op:
        batch_op.drop_index('ix_curriculum_yccd_yccd')
        batch_op.drop_index(batch_op.f('ix_curriculum_yccd_id'))
        batch_op.drop_index('ix_curriculum_yccd_curriculum')

    op.drop_table('curriculum_yccd')
    with op.batch_alter_table('classmember', schema=None) as batch_op:
        batch_op.drop_index('ix_classmember_student')
        batch_op.drop_index(batch_op.f('ix_classmember_id'))
        batch_op.drop_index('ix_classmember_class_student')

    op.drop_table('classmember')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index('ix_assignment_quiz')
        batch_op.drop_index(batch_op.f('ix_assignment_id'))
        batch_op.drop_index('ix_assignment_class_deadline')
        batch_op.drop_index('ix_assignment_class_active')

    op.drop_table('assignment')
    with op.batch_alter_table('yccd', schema=None) as batch_op:
        batch_op.drop_index('ix_yccd_subject_grade')
        batch_op.drop_index(batch_op.f('ix_yccd_id'))
        batch_op.drop_index('ix_yccd_grade')

    op.drop_table('yccd')
    with op.batch_alter_table('teacherpage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacherpage_slug'))
        batch_op.drop_index(batch_op.f('ix_teacherpage_id'))

    op.drop_table('teacherpage')
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_subject_grade')
        batch_op.drop_index('ix_quiz_status_visibility')
        batch_op.drop_index(batch_op.f('ix_quiz_id'))
        batch_op.drop_index('ix_quiz_created_by')
        batch_op.drop_index('ix_quiz_created_at')

    op.drop_table('quiz')
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_user_created')
        batch_op.drop_index(batch_op.f('ix_exam_id'))
        batch_op.drop_index('ix_exam_hash_status')
        batch_op.drop_index(batch_op.f('ix_exam_file_hash'))

    op.drop_table('exam')
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_index('ix_curriculum_subject_grade')
        batch_op.drop_index(batch_op.f('ix_curriculum_id'))
        batch_op.drop_index('ix_curriculum_grade_chapter')
        batch_op.drop_index('ix_curriculum_grade')

    op.drop_table('curriculum')
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_index('ix_class_teacher_active')
        batch_op.drop_index(batch_op.f('ix_class_id'))
        batch_op.drop_index(batch_op.f('ix_class_code'))

    op.drop_table('class')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_full_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index('ix_subject_grade_range')
        batch_op.drop_index('ix_subject_category')

    op.drop_table('subject')
    # ### end Alembic commands ###
